name: linguapp_melos
publish_to: "none"
version: 0.0.1
description: "Required for melos"

environment:
  sdk: ^3.4.4

melos:
  sdkPath: .fvm/flutter_sdk

dev_dependencies:
  melos: ^6.1.0

flutter:
  uses-material-design: true